CREATE TABLE public."user" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone int4 NOT NULL,
	ref_id varchar(255) NOT NULL,
	salary int4 NOT NULL,
	"type" varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	CONSTRAINT uk_kiqfjabx9puw3p1eg7kily8kg UNIQUE (password),
	CONSTRAINT uk_sb8bbouer5wak8vyiiy4pf2bx UNIQUE (username),
	CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE public.membertype (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	max float8 NOT NULL,
	min float8 NOT NULL,
	"type" varchar(255) NOT NULL,
	CONSTRAINT membertype_pkey PRIMARY KEY (id),
	CONSTRAINT uk_nvw2m6d8bbeqno7qrq2ra153e UNIQUE (type)
);